name: open_mail_app_plus
description: This library provides the ability to query the device for installed email apps and open those apps
version: 0.0.2
homepage: https://github.com/binSaed/open_mail_app_plus

environment:
  sdk: ^3.6.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  url_launcher: ^6.3.1
  platform: ^3.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:

  plugin:
    platforms:
      android:
        package: app.istoria.open_mail_app_plus
        pluginClass: OpenMailAppPlusPlugin
      ios:
        package: app.istoria.open_mail_app_plus
        pluginClass: OpenMailAppPlusPlugin
